QWaylandQuickShellSurfaceItemPrivate: Drop unused lambda capture
Drop unused lambda capture in order to fix

    .../qt5/qtwayland/src/compositor/extensions/qwaylandquickshellsurfaceitem.cpp:339:18: error: lambda capture 'this' is not used [-Werror,-Wunused-lambda-capture]
      339 |     auto skip = [this, putOnTop, putOnBottom](QQuickItem *item) {
          |                  ^~~~~
    .../qt5/qtwayland/src/compositor/extensions/qwaylandquickshellsurfaceitem.cpp:372:18: error: lambda capture 'this' is not used [-Werror,-Wunused-lambda-capture]
      372 |     auto skip = [this, putOnTop, putOnBottom](QQuickItem *item) {
          |                  ^~~~~
    2 errors generated.

This amends c9126f06afdfb116b7ba202512c06c0bbbc93ed2.

Change-Id: I89432c3e939292b183421b5952316861df2657c3
Reviewed-by: Konstantin Ritt <ritt.ks@gmail.com>