Drop unused LinuxDmabufFeedback::m_clientBufferIntegration
This addresses this issue seen in a clang 21 build on
Debian testing:

    In file included from .../qt5/qtwayland/src/hardwareintegration/compositor/linux-dmabuf-v1/linuxdmabuf.cpp:4:
    .../qt5/qtwayland/src/hardwareintegration/compositor/linux-dmabuf-v1/linuxdmabuf.h:106:41: error: private field 'm_clientBufferIntegration' is not used [-Werror,-Wunused-private-field]
      106 |     LinuxDmabufClientBufferIntegration *m_clientBufferIntegration;
          |                                         ^
    1 error generated.

Amends a8cd817904075b6297e5854859904ecc7488b79e.

Change-Id: Iad389035cba681872221712864f510bc2f551efe
Reviewed-by: Eskil Abrahamsen Blomfeldt <eskil.abrahamsen-blomfeldt@qt.io>